### ISSUE TITLE
Request: Add the :keywords? option to wrap-json-params

### ISSUE THREAD

**Issue by Malabarba** [ring-clojure/ring-json#36]
This option is only available to `wrap-json-body`, but it seems sensible that it would also be applicable to `wrap-json-params`.

**Comment by weavejester** [comment]
You can use `wrap-keyword-params` for this. Adding `:keywords?` to `wrap-json-params` would make it inconsistent with all the other `wrap-*-params` functions, which always deliver maps that have string keys.

**Comment by Malabarba** [comment]
That's good to know. Thanks!
