### ISSUE TITLE
Getting an input stream instead of a map

### ISSUE THREAD

**Issue by hmgibson23** [ring-clojure/ring-json#38]
I might be missing something but with ```wrap-json-body {keywords? true}``` I'm getting an HttpInputStream rather than a map.

Not sure what I'm doing wrong here.

**Comment by weavejester** [comment]
Is the Content-Type header of the request correct?

**Comment by hmgibson23** [comment]
Yes

**Comment by hmgibson23** [comment]
Okay I figured it out.
