### ISSUE TITLE
Support for non-object JSON body

### ISSUE THREAD

**Issue by eryi** [ring-clojure/ring-json#41]
On line 48 of json.cli :
```clojure
(defn- assoc-json-params [request json]
  (if (map? json)
    (-> request
        (assoc :json-params json)
        (update-in [:params] merge json))
    request))
```
The `map?` mysteriously filters out perfectly valid JSON strings and arrays. Why is this so?

**Comment by weavejester** [comment]
Because the `wrap-json-params` middleware treats JSON bodies as a map of parameters. If the request body isn't a JSON object, it can't treat it as a map of parameters.

You'll note that `wrap-json-body` will accept any valid JSON data.

**Comment by eryi** [comment]
I guess the confusing part is that while malformed JSON throws an error, properly formatted non-objects JSON gets silently discarded. Would it be a good idea for wrap-json-params to treat non-objects as malformed and throw errors?

**Comment by weavejester** [comment]
`wrap-json-params` works the same way as `wrap-params`, in that it only assocs valid parameters.

In general, consider `wrap-json-params` as a version of `wrap-params` that works with JSON. Most of the time you'll want to use `wrap-json-body` instead. `wrap-json-params` might even be deprecated in future versions.
