### ISSUE TITLE
Private functions vs public in the package

### ISSUE THREAD

**Issue by Heliosmaster** [ring-clojure/ring-json#48]
There are some functions that might be useful, in general (e.g. https://github.com/ring-clojure/ring-json/blob/master/src/ring/middleware/json.clj#L7), but can't be used because they are private.

What is the rationale behind this? Why not make them public?

**Comment by weavejester** [comment]
Private functions can be altered without affecting the public API. Every function we make public is an extra function we can't easily change without affecting backward compatibility.
