### ISSUE TITLE
Decode request body according to character-encoding

### ISSUE THREAD

**Issue by liuchunhua** [ring-clojure/ring-json#49]
when I post request include chinese word,param includes "??"
```clojure
(defn- read-json [request & [{:keys [keywords? bigdecimals?]}]]
  (if (json-request? request)
    (if-let [body (:body request)]
      (let [body-string (slurp body)]
```

**Comment by weavejester** [comment]
It sounds like an encoding problem. The `slurp` should take the encoding from the request headers, or default to UTF-8.

A patch to fix this would be welcome.

**Comment by liuchunhua** [comment]
Ok,I pull a request.
