### ISSUE TITLE
wrap response builds whole string

### ISSUE THREAD

**Issue by pete23** [ring-clojure/ring-json#58]
I have a usecase where I’m returning a large amount of data from a resultset, lazily. Using wrap response attempts to build the whole string on heap.

I have a hacked fork which uses generate-stream and an InputStream response to
be more parsimonious about resources.

Is this something you’d be interested in a PR for? If so I may clean what I have up and fix tests etc.

**Comment by pete23** [comment]
I haven’t bothered even doing that tbh, I just always stream. I guess there’s overhead to setting up the writer/stream machinery that we might want to avoid for the general case? If so the laziness of the seq might be a reasonable guess for whether we want streaming maybe? Hmmm. I’ll clean up and submit a first cut and maybe it’ll be more obvious to me then.

**Comment by pete23** [comment]
PR in the hopper. Let me know if you need any further work on it.

**Comment by pete23** [comment]
Hi, any plans to cut a release? I’m quite keen to throw my hacked versions away! :-)

**Comment by weavejester** [comment]
Released 0.5.0.
